AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  TELEGRAMBOTTOKEN:
    Type: String
  ALLOWEDUSERNAMES:
    Type: String

Resources:
  TelegramBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.12
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TELEGRAMBOTTOKEN
          ALLOWED_USERNAMES: !Ref ALLOWEDUSERNAMES
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PillSyncBot
      Events:
        TelegramWebhook:
          Type: Api
          Properties:
            Path: /telegram
            Method: POST
        ReminderTrigger:
          Type: Schedule
          Properties:
            Schedule: "rate(5 minutes)"

  PillSyncBot:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PillSyncBot
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: chat_id
          AttributeType: S
      KeySchema:
        - AttributeName: chat_id
          KeyType: HASH

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/telegram"
